ads = [
    {
        "id": 1,
        "type": "rent",
        "title_uk": "1-кімнатна на Оболоні",
        "title_en": "1-room in Obolon",
        "price": "12 000 грн",
        "photo": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6IjAwamQ2cDdhNXl0bzItQVBMIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.wcrjmW4t3PDh9bqvSHaaZs8ywutV2orGyhA1fCrdoNc/image;s=1280x1024;q=80",
        "district": "Оболонь",
        "rooms": "1",
    },
    {
        "id": 2,
        "type": "rent",
        "title_uk": "2-кімнатна в Центрі",
        "title_en": "2-room in City Center",
        "price": "20 000 грн",
        "photo": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6Im02N3gyeHN0eTdhMjItRUNPU1lTVEVNIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.Y718ITfFGenqTvuQiKnEmq1h5iOvxFuBUTtabL3NqM8/image;s=1280x1024;q=80",
        "district": "Центр",
        "rooms": "2",
    },
    {
        "id": 3,
        "type": "rent",
        "title_uk": "3-кімнатна на Лівому березі",
        "title_en": "3-room on Left Bank",
        "price": "25 000 грн",
        "photo": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6InV0ejUycHY2Zmk4dy1FQ09TWVNURU0iLCJ3IjpbeyJmbiI6ImVudmZxcWUxYXk0azEtQVBMIiwicyI6IjE0IiwicCI6IjEwLC0xMCIsImEiOiIwIn1dfQ.NnpvzMPvktkRPF0G3Ote0b6RK1BeevRUPb5ORRzfdOw/image;s=314x236;q=80",
        "district": "Лівий берег",
        "rooms": "3",
    },
    {
        "id": 4,
        "type": "rent",
        "title_uk": "1-кімнатна в Шевченківському районі",
        "title_en": "1-room in Shevchenkivskyi district",
        "price": "10 000 грн",
        "photo": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6InlhY2pkZW40MnlhNzMtRUNPU1lTVEVNIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.nQSyKyIqkSMod97E9B5V75z7aaWIZ45Esl-1pZaT6_Y/image;s=314x236;q=80",
        "district": "Шевченківський",
        "rooms": "1",
    },
    {
        "id": 5,
        "type": "rent",
        "title_uk": "2-кімнатна на Позняках",
        "title_en": "2-room in Pozniaky",
        "price": "17 500 грн",
        "photo": "https://ireland.apollo.olxcdn.com/v1/files/eyJmbiI6Im02N3gyeHN0eTdhMjItRUNPU1lTVEVNIiwidyI6W3siZm4iOiJlbnZmcXFlMWF5NGsxLUFQTCIsInMiOiIxNCIsInAiOiIxMCwtMTAiLCJhIjoiMCJ9XX0.Y718ITfFGenqTvuQiKnEmq1h5iOvxFuBUTtabL3NqM8/image;s=1280x1024;q=80",
        "district": "Позняки",
        "rooms": "2",
    },
]
